name: blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update this repo's README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.ioiox.com/feed"

      - name: Notification - Failure
        if: ${{ failure() }}
        run: |
          echo "Failed to update README with latest blog posts"
